#### widgets-docker
version: '2.2'
services:
  cs:
    image: hlds/server:alpha
    volumes:
      - ./server.cfg:/opt/hlds/cstrike/server.cfg
    restart: always
    logging:
        driver: json-file
        options:
          max-size: 5M
    ports:
        - 27015:27015/udp
    environment:
      - START_MAP=cs_italy
      - ADMIN_STEAM=0:1:1234566
      - SERVER_NAME="Kien server"
    command: -insecure +log
